name: pandora1
version: 1
build:
  - name: Build
    command: docker build -t railway-app .
    path: .
deploy:
  - name: Deploy
    command: docker run -e PANDORA_CLOUD=cloud -e PANDORA_SERVER=0.0.0.0:8899 -p 8899:8899 -d railway-app
